language: node_js
node_js:
  - "0.10"

before_install:
  - sudo add-apt-repository -y ppa:mapnik/v2.2.0
  - sudo apt-get update -y
  - sudo apt-get install libboost-dev libgdal1h libgdal-dev libmapnik libmapnik-dev

install: make all
script: make test
